
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name:  prometheus
  scrape_interval: 5s
  static_configs:
    - targets: ["localhost:9090"]
- job_name: grafana
  scrape_interval: 5s
  static_configs:    
    - targets: ["13.59.132.215:3005"]
- job_name: web
  scrape_interval: 5s
  static_configs:
    - targets: ["13.59.132.215:7000"]
      

    
    
  
